stages:
  - build

build_project:
  stage: build
  script:
    - cp "$DEV_TEAM_FILE" Xcode-config/DEVELOPMENT_TEAM.xcconfig
    - xcodebuild -workspace "./Cog.xcodeproj/project.xcworkspace" -scheme Cog -configuration Release build -derivedDataPath "./CogBuilds"