
name: Check if Cog buildable
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Cog for Intel
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup DEVELOPMENT_TEAM
        env:
          MAC_DEVELOPMENT_TEAM: ${{ secrets.MAC_DEVELOPMENT_TEAM }}
        run: |
          echo "DEVELOPMENT_TEAM = $MAC_DEVELOPMENT_TEAM" > Xcode-config/DEVELOPMENT_TEAM.xcconfig
      - name: Install application certificate
        uses: apple-actions/import-codesign-certs@v1
        with: 
          keychain: ${{ github.run_id }}
          keychain-password: ${{ github.run_id }}
          p12-file-base64: ${{ secrets.MAC_APPLICATION_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.MAC_APPLICATION_CERTIFICATE_PASSPHRASE }}
      - name: Run xcodebuild
        run: >
          xcodebuild
            -workspace Cog.xcodeproj/project.xcworkspace
            -scheme Cog
            -configuration Debug
            -derivedDataPath output
            build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Cog
          path: output/Build/Products/Debug/Cog.app
