
name: Check if Cog buildable
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Cog for Intel
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run xcodebuild
        run: >
          xcodebuild
            -workspace Cog.xcodeproj/project.xcworkspace
            -scheme Cog
            -configuration Debug
            -derivedDataPath output
            build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Cog
          path: output/Build/Products/Debug/Cog.app
